### PR TITLE
Add repeat_until_calc_array_type KST spec

### PR DESCRIPTION
**Pull request by generalmimon**
See https://github.com/kaitai-io/kaitai_struct_tests/pull/51, too impatient to wait for @ams-tschoening 🙂

### CODE REVIEW

**Comment by ams-tschoening** [comment]
I've already created a KST-file as well: https://github.com/ams-ts-kaitai/tests/commit/d7ec8936054659918ae06d4521c5ee00611765bd

**Comment by generalmimon** [comment]
I actually noticed, there is [wrong `id` though](https://github.com/ams-ts-kaitai/tests/commit/d7ec8936054659918ae06d4521c5ee00611765bd#diff-37d685bc77b1f11d5dd0cdcbe77ae3acR2) and I didn't want to bother you with this, sorry. If you insist on finishing this yourself, I can close this PR and you can create your own 😉 

Speaking of which, have you ever managed to translate some KST spec using the translator? It'd be nice if you could generate tests for all languages using KST next time, not just Ruby.

**Comment by ams-tschoening** [comment]
Feel free to leave this open, only wanted to address your critics.

What do you mean by Ruby-only? Doesn't `spec_kst_to_all` handle creating tests for all languages? I only committed the KST-file itself, but the script seemed to have run successfully. Besides that, I mostly focus on what I need, which is Java and Ruby, because things break to often already on Windows and I need to fix those problems first.

**Comment by generalmimon** [comment]
> What do you mean by Ruby-only? Doesn't `spec_kst_to_all` handle creating tests for all languages?

It does, provided that you created correct .kst spec. But the tests generated from KST are always commited (just look into the [kaitai_struct_tests commit history](https://github.com/kaitai-io/kaitai_struct_tests/commits/master), all the "Regen ..." commits are adding generated test codes to the repo), so if you commit them together with your KST spec, you save @GreyCat's time. 

Moreover, you should always run `spec_kst_to_all` locally, because you're basically responsible for the KST spec you create. How do you know that the generated tests will work as you intend without generating them from the KST? If the KST translator fails to run or generates a test code in some language that you're not comfortable with, you should either change the generated test code or edit the KST spec.

**Comment by ams-tschoening** [comment]
> [...]so if you commit them together with your KST spec, you save @GreyCat's time.

My KST was an example to get familiar with a yet undocumented feature, which at some part even failed to work properly, so not committing its results and instead asking about them first made sense of course.

> Moreover, you should always run spec_kst_to_all locally

And I did obviously.

> because you're basically responsible for the KST spec you create.

As this project works collaboratively, I guess there's a good chance that other people happily fix things I might have missed, like I regularly fix things others might have missed. You are sending bad vibes and I don't think I'm interested in further discussion. Have a nice day.

**Comment by generalmimon** [comment]
> As this project works collaboratively, I guess there's a good chance that other people happily fix things I might have missed, like I regularly fix things others might have missed. You are sending bad vibes and I don't think I'm interested in further discussion.

Sorry, I exaggerated it, you're right. This is an open-source project, all contributors are volunteers that do it in their free time and we should be grateful for everything they do, not blaming them. I should have realized that.

@GreyCat, can this be merged? I'd like to push things forward so that 0.9 version could finally be released, but unfortunately most issues from the [**v0.9 Milestone**](https://github.com/kaitai-io/kaitai_struct/milestone/6) are C++ specific and I have no experience with it. But I think I can help with https://github.com/kaitai-io/kaitai_struct/issues/561 and it would be nice to have this test for all languages in CI to see what's left to fix.

**Pull request merged**
