### PR TITLE
Add MIT License

### PR DESCRIPTION
**Pull request by cugu**
See https://github.com/kaitai-io/kaitai_struct/issues/474

### CODE REVIEW

**Comment by GreyCat** [comment]
Technically and legally, we should reach out to [contributors](https://github.com/kaitai-io/kaitai_struct_tests/graphs/contributors) of tests repo and get their approvals to license their work in tests repo using MIT license:

- [x] @GreyCat
- [ ] @LogicAndTrick
- [ ] @tschoening / @ams-tschoening
- [ ] @adrianherrera
- [ ] @sealmove
- [ ] @koczkatamas
- [ ] @jchv
- [x] @cugu
- [ ] @nolta
- [ ] @modernikarus
- [ ] @cherue
- [ ] @CWood1
- [ ] @mickdekkers
- [ ] @markbook2
- [ ] @adamiwaniuk
- [ ] @13rac1

An ask for everyone mentioned on this list: please provide your approval / disapproval to license your work as per MIT license in this issue?

**Comment by jchv** [comment]
I approve of this.

**Comment by ams-tschoening** [comment]
I approve this.

**Comment by LogicAndTrick** [comment]
Yep, works for me.

**Comment by adrianherrera** [comment]
This is fine by me.

**Comment by nolta** [comment]
Sure, approved.

**Comment by 13rac1** [comment]
I approve.

**Comment by koczkatamas** [comment]
I approved myself :D

**Comment by jchv** [comment]
# Status
Here's where we're at.

- @sealmove: E-mail is available via git log. [Contributions](https://github.com/kaitai-io/kaitai_struct_tests/commits?author=sealmove)
- @modernikarus: E-mail is available via git log. [Contributions](https://github.com/kaitai-io/kaitai_struct_tests/commits?author=modernikarus)
- @cherue: :x: E-mail is not available via git log. &bullet; [Contributions](https://github.com/kaitai-io/kaitai_struct_tests/commits?author=cherue)
- @CWood1: E-mail is available via git log. [Contributions](https://github.com/kaitai-io/kaitai_struct_tests/commits?author=CWood1)
- @mickdekkers: E-mail is available via git log. [Contributions](https://github.com/kaitai-io/kaitai_struct_tests/commits?author=mickdekkers)
- @markbook2: :x: E-mail is not available via git log [Contributions](https://github.com/kaitai-io/kaitai_struct_tests/commits?author=markbook2)
- @adamiwaniuk: E-mail is available via git log. [Contributions](https://github.com/kaitai-io/kaitai_struct_tests/commits?author=adamiwaniuk)

Here is a table of the currently missing approvals. The word 'significant' here is meant to refer to contributions that are large enough to be considered expressions. (notably, I am not trying to suggest such contributions are not meaningful to the project, just looking at this from a point of view strictly focused on copyright/relicensing.) The bar for originality and non-triviality in terms of copyright differ by jurisdiction, so only the absolute smallest and most trivial contributions will be considered not significant in this case. (Just to be sure, I am not a lawyer, and this does not constitute legal advice.)

Developer|Commits|Added|Removed|Significant?|Have Email
:---|:---|:---|:---|:---|:---
@sealmove | 8 | 1,318 | 37 | :+1: Yes | :heavy_check_mark: 
@modernikarus | 2 | 85 | 0 | :+1: Yes | :heavy_check_mark: 
@cherue | 2 | 2 | 2 | No<sup>[1]</sup> | :x: 
@CWood1 | 2 | 2,122 | 52 | :+1: Yes | :heavy_check_mark:
@mickdekkers | 1 | 41 | 0 | :+1: Yes | :heavy_check_mark: 
@markbook2 | 1 | 8 | 0 | Maybe?<sup>[2]</sup> | :x:
@adamiwaniuk | 1 | 66 | 0 | :+1: Yes | :heavy_check_mark: 

   <sup>[1]</sup> Contribution from @cherue is likely trivial enough to fall under the umbrella of not being a copyrightable expression. It is a total of 4 characters, changing two different version numbers.

   <sup>[2]</sup> The sole contribution adds a few declarations to tests. Although relatively small, I believe these changes may clear the bar for copyrightability in some jurisdictions.

## What to do

(I have no decision making power, this is just my personal suggestion.)

*   Now:
    -   Attempt to reach developers via e-mail? This should be coordinated in order to avoid having multiple people do it. I am not posting e-mail addresses here out of respect for privacy.
    -   Consider excluding @cherue from the list of users if nobody is able to contact them. No offense if you ever read this @cherue, all contributions are valuable.

*   In the event not everyone can be reached:
    -   Undo commits from developers that we are unable to get consent from.
    -   Apply license change.
    -   Possibly rewrite changes from scratch based on their intended effects, or simply continue to try to get consent from original authors to reapply later.

**Comment by mickdekkers** [comment]
Hi there, I just noticed this ping 🙂 

I approve 👍

**Comment by cugu** [comment]
I'll send out some mails.

**Comment by cugu** [comment]
@adamiwaniuk's email account does not exist any more.

**Comment by sealmove** [comment]
I approve.

**Comment by modernikarus** [comment]
I approve.

**Comment by cherue** [comment]
I approve and I'd like to add that all my contributions to any of the kaitai-io organization repositories are licensed as CC0.

**Comment by adamiwaniuk** [comment]
I approve.

**Comment by CWood1** [comment]
I approve of the change

**Comment by GreyCat** [comment]
Hurray! Looks like we only miss consent of @markbook2. I'll try to reach out to them.

**Comment by cherue** [comment]
Looking at [@markbook2's commit](https://github.com/kaitai-io/kaitai_struct_tests/commit/e38d2f348db98e7954692dd68d93aa8feb87bb06) there are two types of changes:
1. Two tests are marked as skipped, this can only be done one way so it can be copied
2. Two tests are marked as "not risky"

The two tests are "risky" because they do not have any assertions, see [PHPUnit docs](https://phpunit.readthedocs.io/en/9.0/risky-tests.html). PHPUnit calls tests like these "useless" but they are not in this case. What is being tested is that the generated PHP is syntactically correct and that it parses some data file without throwing errors. Instead of marking individual tests as "not risky" it is possible to tell PHPUnit that this type of test is ok by passing the `--dont-report-useless-tests` command line option in `run-php`.

So, if the decision was made to revert that commit the reimplementation could be:
- Add `$this->markTestSkipped();` to `kaitai_struct_tests/spec/php/Debug0Test.php` and `kaitai_struct_tests/spec/php/DebugEnumNameTest.php`
- Add `--dont-report-useless-tests` to ` kaitai_struct_tests/run-php `

**Comment by GreyCat** [comment]
@markbook2: you seem to be busy these days, but any chance you can sign this off, so we can move forward with adding the license?

**Comment by GreyCat** [comment]
@cherue @cugu Phew, looks like we're now in full agreement and ready to apply the license. Thanks for this tremendous job, everyone!

**Pull request merged**
